### ISSUE TITLE
Tidy style 

### ISSUE THREAD

**Issue by lisahns** [fac25/abby-abdulla-karwan-lisa-server#31]
style message <p class = "post-message"

**Comment by Abbbyccc** [comment]
- name input needs some padding
- error message doesn't display well
- post blog message area should be able to display large data
- try to make Like and Delete button in the same block
- accessibility
- add footer
- rogue comma (if you can find it)
@lisahns would you like to add any issues? thank you

**Comment by ivan-unfolds** [comment]
overall, I really the clean minimal styling you guys have applied!

I did pick up on some small issues though: 

* label for post input spans two lines, it would look nicer if it were just one
<img width="205" alt="CleanShot 2022-09-22 at 18 07 56@2x" src="https://user-images.githubusercontent.com/12462448/191797930-c79b4950-a46a-4d47-8c97-8e7dd3b84145.png">

* it would look nicer if there was some padding in mobile view, the content goes all the way to the edge of the screen at the moment
<img width="414" alt="CleanShot 2022-09-22 at 18 08 09@2x" src="https://user-images.githubusercontent.com/12462448/191798182-fb81254d-240c-46a1-9e6e-a8ff8c88c5d2.png">

btw @Abbbyccc, I find it helpful with styling issues to add screenshots to highlight the problems as explicitly as possible
