### ISSUE TITLE
Accessibility in Lighthouse

### ISSUE THREAD

**Issue by Joe-Lindie** [fac25/abby-abdulla-karwan-lisa-server#34]
Hey, 

Love the site! There is one accessibility issue you could maybe work on. On the server.js file you could maybe wrap the `post list`  variable in <li></li> tags. This variable is being called on line 85 between the <ul> tag and the only children of <ul> can be <li>

Your accessibility is currently at 91 , but add the tags may bump it up a little

**Comment by Abbbyccc** [comment]
- Relates #41
