### ISSUE TITLE
Server.test.js file last test 

### ISSUE THREAD

**Issue by Joe-Lindie** [fac25/abby-abdulla-karwan-lisa-server#42]
Hello again, 

On the last test function inside the server.test.js , I think you need to change the regex (line 42) from `message` to `hello` as you have set the body (line 33) to `  body: name=lisa&message=hello`

Currently you are testing to see if the body contains the string 'message' but this will _always_  be in the body (no matter what the form's input value was) since 'message' is the name attribute of the textarea input.

**Comment by flare-s** [comment]
Thanks, Joe!
